version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://mongodb:27017/qpDatabase
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
